services:
  datadog-agent:
    image: datadog/agent:latest
    env_file:
      - ../.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
  
  python-json-logs:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=python-json-logs
      - DD_ENV=dev
      - DD_VERSION=1.0.0
    depends_on:
      - datadog-agent
