apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-prisma-app
  labels:
    app: node-prisma-app
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: node-prisma-app
    tags.datadoghq.com/version: "1234"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-prisma-app
  template:
    metadata:
      labels:
        app: node-prisma-app
        tags.datadoghq.com/env: dev
        tags.datadoghq.com/service: node-prisma-app
        tags.datadoghq.com/version: "1234"
    #    admission.datadoghq.com/enabled: "true"
    #  annotations:
    #    admission.datadoghq.com/js-lib.version: v5.61.1
    spec:
      containers:
        - name: node-prisma-app
          image: node-prisma-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          # Environment variables for Datadog APM instrumentation
          env:
            - name: DD_TRACE_DEBUG
              value: "true"
            # Datadog agent configuration
            - name: DD_AGENT_HOST
              value: "datadog-agent"
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_LOGS_INJECTION
              value: "true"
            # Datadog unified service tagging
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            # Database connection environment variables
            - name: DATABASE_URL
              value: "mysql://prisma:password@mysql-service:3306/node_prisma_db"
            - name: MYSQL_HOST
              value: "mysql-service"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "node_prisma_db"
            - name: MYSQL_USER
              value: "prisma"
            - name: MYSQL_PASSWORD
              value: "password"
