# There is no microsoft odbc package for debian12 so we stick with 11 for now (documentation is wrong and outdated)
FROM datadog/agent:7.52.0

RUN if ! [[ "18.04 20.04 22.04 23.04 24.04" == *"$(lsb_release -rs)"* ]]; \
then \
    echo "Ubuntu $(lsb_release -rs) is not currently supported."; \
    exit 1;  fi

RUN curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc

RUN curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list

RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18
ENV PATH="$PATH:/opt/mssql-tools18/bin"

# optional: for unixODBC development headers
RUN apt-get install -y unixodbc-dev
