services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    networks:
      - test_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - test_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  django-pymongo-motor-app:
    env_file:
      - ../../.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-pymongo-motor-app
    ports:
      - "8000:8000"
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=password123
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      # Datadog APM settings
      - DD_TRACE_ENABLED=true
      - DD_VERSION=1.0.0
      - DD_ENV=dev
      - DD_SERVICE=django-pymongo-motor-app
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_TRACE_DJANGO_ENABLED=true
      - DD_TRACE_DEBUG=true
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - test_network
    restart: "no"

  celery-worker:
    env_file:
      - ../../.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-worker
    command: celery -A myproject worker --loglevel=info --concurrency=2
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=password123
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      # Datadog APM settings
      - DD_TRACE_ENABLED=true
      - DD_VERSION=1.0.0
      - DD_ENV=dev
      - DD_SERVICE=celery-worker
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_TRACE_DEBUG=true
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - test_network
    restart: "no"

  datadog-agent:
    env_file:
      - ../../.env
    image: datadog/agent:latest
    container_name: datadog_agent
    environment:
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOG_LEVEL=error
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
