#!make
########################################################
## .NET ASP App
########################################################
build:
	docker build --no-cache -t dotnet-dbm:latest .

run:
	docker-compose up

stop:
	docker-compose down
