apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    site: datadoghq.com
    tags:
      - "env:dev"
    clusterName: docker-desktop
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
    logLevel: info
    kubelet:
      tlsVerify: false
  features:
    apm:
      instrumentation:
        enabled: true
        targets:
          - name: "default-target"
            ddTraceVersions:
              java: "1"
              python: "3"
              js: "5"
              php: "1"
              dotnet: "3"
              ruby: "2"
    logCollection:
      enabled: true
      containerCollectAll: true
