apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-prisma-app
spec:
  selector:
    app: mysql-prisma-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
