apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  labels:
    app: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "flask-api"
        tags.datadoghq.com/version: "1.0"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/python-lib.version: v3.7.1
    spec:
      containers:
      - name: flask-api
        image: flask-api-dev:latest
        imagePullPolicy: Never
        env:
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_APM_INSTRUMENTATION_DEBUG
            value: "true"
        ports:
        - containerPort: 5000
